  services:
    schema-registry:
      image: confluentinc/cp-schema-registry:${KAFKA_VERSION}
      hostname: schema-registry
      depends_on:
        - kafka-broker-1
        - kafka-broker-2
        - kafka-broker-3
      ports:
        - "8081:8081"
      environment:
        SCHEMA_REGISTRY_HOST_NAME: schema-registry
        SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka-broker-1:9092,PLAINTEXT://kafka-broker-2:9092,PLAINTEXT://kafka-broker-3:9092'
        SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8081'
        SCHEMA_REGISTRY_DEBUG: 'true'
      networks:
        - ${GLOBAL_NETWORK:-kafka}

    kafka-broker-1:
      image: confluentinc/cp-kafka:${KAFKA_VERSION}
      hostname: kafka-broker-1
      ports:
        - "19092:19092"
      environment:
        KAFKA_PROCESS_ROLES: 'broker,controller'
        KAFKA_NODE_ID: 1
        KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
        KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093'
        KAFKA_CONTROLLER_LISTENERS: 'CONTROLLER://0.0.0.0:9093'
        KAFKA_LISTENERS: 'CONTROLLER://0.0.0.0:9093,PLAINTEXT://0.0.0.0:9092,LISTENER_LOCAL://0.0.0.0:19092'
        KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker-1:9092,LISTENER_LOCAL://localhost:19092'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT'
        KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
        KAFKA_COMPRESSION_TYPE: producer
      networks:
        - ${GLOBAL_NETWORK:-kafka}

    kafka-broker-2:
      image: confluentinc/cp-kafka:${KAFKA_VERSION}
      hostname: kafka-broker-2
      ports:
        - "29092:29092"
      environment:
        KAFKA_PROCESS_ROLES: 'broker,controller'
        KAFKA_NODE_ID: 2
        KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
        KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093'
        KAFKA_CONTROLLER_LISTENERS: 'CONTROLLER://0.0.0.0:9093'
        KAFKA_LISTENERS: 'CONTROLLER://0.0.0.0:9093,PLAINTEXT://0.0.0.0:9092,LISTENER_LOCAL://0.0.0.0:29092'
        KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker-2:9092,LISTENER_LOCAL://localhost:29092'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT'
        KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
        KAFKA_COMPRESSION_TYPE: producer
      networks:
        - ${GLOBAL_NETWORK:-kafka}

    kafka-broker-3:
      image: confluentinc/cp-kafka:${KAFKA_VERSION}
      hostname: kafka-broker-3
      ports:
        - "39092:39092"
      environment:
        KAFKA_PROCESS_ROLES: 'broker,controller'
        KAFKA_NODE_ID: 3
        KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
        KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093'
        KAFKA_CONTROLLER_LISTENERS: 'CONTROLLER://0.0.0.0:9093'
        KAFKA_LISTENERS: 'CONTROLLER://0.0.0.0:9093,PLAINTEXT://0.0.0.0:9092,LISTENER_LOCAL://0.0.0.0:39092'
        KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker-3:9092,LISTENER_LOCAL://localhost:39092'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT'
        KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
        KAFKA_COMPRESSION_TYPE: producer
      networks:
        - ${GLOBAL_NETWORK:-kafka}

  networks:
    ${GLOBAL_NETWORK:-kafka}:
      external: true